// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHcnNEJC9uPJ5iiFoZTcDOR7IlH63ufW0',
    appId: '1:923930251963:web:df929eac73f116033d8f9e',
    messagingSenderId: '923930251963',
    projectId: 'fir-test-5c30f',
    authDomain: 'fir-test-5c30f.firebaseapp.com',
    storageBucket: 'fir-test-5c30f.appspot.com',
    measurementId: 'G-J8DDX44M04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEIU_PVt_VcqMnYzKLoeLPdVsnu6NmsJ4',
    appId: '1:923930251963:android:12f05dcdefd50b673d8f9e',
    messagingSenderId: '923930251963',
    projectId: 'fir-test-5c30f',
    storageBucket: 'fir-test-5c30f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_SYlgNxTGSQDgjxV6ZGQZT5popDQ32ik',
    appId: '1:923930251963:ios:d385f3398bb0c11c3d8f9e',
    messagingSenderId: '923930251963',
    projectId: 'fir-test-5c30f',
    storageBucket: 'fir-test-5c30f.appspot.com',
    iosClientId: '923930251963-k0f0lfvsdo04r291e2ah8hmbh95b8ccs.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_SYlgNxTGSQDgjxV6ZGQZT5popDQ32ik',
    appId: '1:923930251963:ios:1979d49ee315e5c03d8f9e',
    messagingSenderId: '923930251963',
    projectId: 'fir-test-5c30f',
    storageBucket: 'fir-test-5c30f.appspot.com',
    iosClientId: '923930251963-tuu32io1k35385tq43tfqbrgt1tmdtuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
